.TH "mur" 3 "Mon May 10 2021" "Documentation_Projet_Bomber" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mur
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <terrain\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBpos_x\fP"
.br
.ti -1c
.RI "int \fBpos_y\fP"
.br
.ti -1c
.RI "bool \fBexiste\fP"
.br
.ti -1c
.RI "bool \fBexterieur\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file terrain\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "bool mur::existe"

.PP
Definition at line 6 of file terrain\&.h\&.
.SS "bool mur::exterieur"

.PP
Definition at line 7 of file terrain\&.h\&.
.SS "int mur::pos_x"

.PP
Definition at line 5 of file terrain\&.h\&.
.SS "int mur::pos_y"

.PP
Definition at line 5 of file terrain\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Documentation_Projet_Bomber from the source code\&.
