.TH "src/terrain.cpp" 3 "Mon May 10 2021" "Documentation_Projet_Bomber" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/terrain.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'terrain\&.h'\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <cassert>\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "const char \fBterrain2\fP [21][21]"
.br
.RI "création du terrain "
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const char terrain2[21][21]"
\fBInitial value:\fP
.PP
.nf
=
{
    "####################",
    "#\&.\&.\&.MM\&.\&.M\&.\&.M\&.\&.MM\&.\&.\&.#",
    "#\&.MMMM\&.\&.M\&.\&.M\&.\&.MMMM\&.#",
    "#MMMMMMMM\&.\&.MMMMMMMM#",
    "#\&.\&.\&.\&.\&.\&.\&.M\&.\&.M\&.\&.\&.\&.\&.\&.\&.#",
    "#MMMMMMMMMMMMMMMMMM#",
    "#MMMM\&.\&.\&.\&.M\&.\&.\&.\&.\&.MMMM#",
    "#MM\&.\&.\&.\&.\&.\&.\&.\&.\&.\&.\&.\&.\&.\&.MM#",
    "#\&.MMMMMMMMMMMMMMMM\&.#",
    "#\&.\&.\&.\&.\&.\&.\&.\&.\&.\&.\&.\&.\&.\&.\&.\&.\&.\&.#",
    "#\&.MMMMMMMMMMMMMMMM\&.#",
    "#MM\&.\&.\&.MM\&.M\&.MM\&.\&.\&.\&.MM#",
    "#\&.\&.\&.\&.\&.\&.\&.\&.M\&.\&.\&.\&.\&.\&.\&.\&.\&.#",
    "#\&.\&.\&.\&.MMMMMMMMM\&.\&.\&.\&.\&.#",
    "#\&.\&.\&.\&.\&.\&.\&.\&.M\&.\&.\&.\&.\&.\&.\&.\&.\&.#",
    "#MM\&.\&.\&.\&.\&.\&.M\&.\&.\&.\&.\&.\&.\&.MM#",
    "#MMMMM\&.\&.\&.M\&.\&.\&.\&.MMMMM#",
    "#\&.MMMM\&.\&.\&.M\&.\&.\&.\&.MMMM\&.#",
    "#\&.\&.\&.MM\&.\&.\&.M\&.\&.\&.\&.MM\&.\&.\&.#",
    "####################"
}
.fi
.PP
création du terrain 
.PP
Definition at line 11 of file terrain\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Documentation_Projet_Bomber from the source code\&.
