.TH "src/Wintxt.h" 3 "Mon May 10 2021" "Documentation_Projet_Bomber" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Wintxt.h
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBWinTXT\fP"
.br
.RI "une fenêtre texte est un tableau 2D de caractères "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBtermClear\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void termClear ()"

.PP
Definition at line 37 of file Wintxt\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Documentation_Projet_Bomber from the source code\&.
