.TH "src/Wintxt.cpp" 3 "Mon May 10 2021" "Documentation_Projet_Bomber" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Wintxt.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Wintxt\&.h'\fP
.br
\fC#include <cassert>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdarg\&.h>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <termios\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBtermMove\fP (int x, int y)"
.br
.ti -1c
.RI "void \fBtermClear\fP ()"
.br
.ti -1c
.RI "void \fBtermInit\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void termClear ()"

.PP
Definition at line 37 of file Wintxt\&.cpp\&.
.SS "void termInit ()"

.PP
Definition at line 46 of file Wintxt\&.cpp\&.
.SS "void termMove (int x, int y)"

.PP
Definition at line 21 of file Wintxt\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Documentation_Projet_Bomber from the source code\&.
